# Generated by Django 3.1.7 on 2021-06-18 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserTyp',
            new_name='UserType',
        ),
    ]
