# Generated by Django 3.1.7 on 2021-06-19 01:16

import apps.users_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0003_auto_20210618_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defendant',
            name='rut',
            field=models.CharField(max_length=13, validators=[apps.users_app.models.ValidarRut]),
        ),
    ]
