# Generated by Django 3.1.7 on 2021-06-19 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0004_auto_20210618_2116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lawsuit_state',
            name='demand_state',
        ),
        migrations.AddField(
            model_name='court',
            name='cod_tribunal',
            field=models.CharField(default='00', max_length=6),
        ),
        migrations.AlterField(
            model_name='court',
            name='comuna',
            field=models.CharField(default='no asigando', max_length=45),
        ),
        migrations.AlterField(
            model_name='court',
            name='name_court',
            field=models.CharField(default='no asigando', max_length=45),
        ),
    ]
