# Generated by Django 3.1.7 on 2021-06-19 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0006_auto_20210619_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawsuit',
            name='cause_rol',
            field=models.CharField(default='no asigando', max_length=45),
        ),
    ]
