# Generated by Django 3.1.7 on 2021-06-19 06:11

import apps.users_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0007_auto_20210619_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defendant',
            name='rut',
            field=models.CharField(max_length=20, validators=[apps.users_app.models.ValidarRut]),
        ),
    ]
